import Home from "./Home"
import Detail from "./Detail"
import Cart from "./Cart"
import Welcome1 from "./Welcome1"
import FaceOil from "./FaceOil"
import Search from "./Search"
import Register from "./Register"
import Login from "./Login"
import CheckOut from "./CheckOut"
import Skin from "./Skin"
import Body from "./Body"
import Hair from "./Hair"
import Profile from "./Proile"
import Payment from "./Payment"
import PayPalComponent from "./PayPal"
import OrderPage from "./OrderPage"
import ConfirmOrdre from "./Confirm"
export {Welcome1,Home,Detail,Cart,FaceOil,Search,Register,Login,CheckOut,Skin,Body,Hair,Profile,Payment,PayPalComponent,OrderPage,ConfirmOrdre}